// 广州咖啡店数据
// 添加新店只需在 coffeeShops 数组末尾追加即可

const coffeeShops = [
    {
        id: "qianyuan-coffee",
        name: "浅原咖啡·Simesp Coffee",
        area: "越秀",
        district: "区庄",
        address: "越秀区东风东路733号羊城同创汇编辑楼1楼101",
        featured: true,
        lat: 23.131959,
        lng: 113.300867,
        tags: ["创意特调", "自烘焙"],
        priceRange: "¥28-45",
        rating: 4.6,
        recommendation: "在浅原合适喝创意咖啡，不会踩雷。坐在吧台看到好几位顾客点特调，又看着咖啡师忙着鲜榨各种食材，看菜单的介绍让我有种想逐杯打卡的欲望~",
        highlights: ["青梅竹马", "白莓林", "秋橘"],
        hours: "周一至周日 7:45-19:30",
        metro: "区庄站 B2 口步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-02-15",
        updatedAt: "2026-06-01",        photos: [],
    },
    {
        id: "kaqi-coffee",
        name: "咖期 KatsCoffee",
        area: "越秀",
        district: "农讲所",
        address: "越秀区文德路仁康里38号首层南侧",
        featured: true,
        lat: 23.12394,
        lng: 113.273095,
        tags: ["自烘焙", "精品手冲"],
        priceRange: "¥18-35",
        rating: 4.8,
        recommendation: "越秀精品小店，自烘豆品质扎实，广州烘焙赛区冠军，咖啡师很愿意交流",
        highlights: ["单品手冲"],
        hours: "周一至周日 11:00-18:00",
        metro: "农讲所站 A 口步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-02-15",
        updatedAt: "2026-06-01",        photos: [],
    },
    {
        id: "huixiang-coffee",
        name: "回响咖啡 The Echo Coffee",
        area: "越秀",
        district: "德政北路",
        address: "越秀区德政北路502-504号首层自编之四",
        featured: true,
        lat: 23.129349,
        lng: 113.274532,
        tags: ["自烘焙", "精品手冲"],
        priceRange: "¥25-45",
        rating: 4.6,
        recommendation: "爱乐压冠军坐镇，念念不忘必有回响，Combo性价比超高（普通豆28元/瑰夏34元）",
        highlights: ["藤椒青提美式", "Combo一豆两喝", "爱乐压手冲"],
        hours: "周一至周日 10:00-21:00",
        metro: "农讲所站步行约 12 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-02-15",
        updatedAt: "2026-06-01",        photos: [],
    },
    {
        id: "tickup-coffee",
        name: "TICK UP COFFEE",
        area: "增城",
        district: "荔城街道",
        address: "广州市增城区新园路3号",
        featured: true,
        lat: 23.299242,
        lng: 113.823428,
        tags: ["精品手冲", "浅烘培"],
        priceRange: "¥20-40",
        rating: 4.8,
        recommendation: "单品豆选品种类丰富，店里有很多黑胶唱片，氛围非常好，出品很稳定，如果你也想听着黑胶、cd喝上一杯好喝的咖啡，我想你会喜欢。",
        highlights: ["汤力美式", "抹茶拿铁", "单品手冲"],
        hours: "周二至周三 周五至周日 11:00-18:00",
        metro: "增城广场站打车 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: true },
        createdAt: "2026-06-01",
        updatedAt: "2026-06-01",        photos: [],
    },
    {
        id: "buzz-coffee",
        name: "Buzz Coffee",
        area: "越秀",
        district: "公园前",
        address: "越秀区起义路197号",
        lat: 23.121349,
        lng: 113.264006,
        tags: ["Combo", "精品手冲", "浅烘培"],
        priceRange: "¥33-78",
        rating: 4.6,
        recommendation: "主理人常在咖啡赛事中亮相，出品稳定，比赛级品质带给大家。",
        highlights: ["单品SOE", "Combo"],
        hours: "周一至周日 10:00-19:00",
        metro: "公园前站 J 口步行 410 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2025-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "whoopee-coffee",
        name: "Whoopee! Coffee",
        area: "海珠",
        district: "江南西",
        featured: true,
        address: "海珠区江南大道中209号103穗花新村月季楼楼下商铺",
        lat: 23.095843,
        lng: 113.275475,
        tags: ["自烘焙", "Combo"],
        priceRange: "¥22-42",
        rating: 4.8,
        recommendation: "江南西宝藏社区小店，复古红门头超吸睛，店里的小狗超级可爱，蛋糕出品非常稳定，好吃不腻",
        highlights: ["Combo", "蛋糕", "SOE美式"],
        hours: "周二周三店休；周一动态调整，周四周五 10:00-18:00（周末12:00-18:00）",
        metro: "江南西站 B 口步行 200 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2021-02-01",
        updatedAt: "2024-12-01",        photos: [],
    },
    {
        id: "sinamon-coffee",
        name: "Sinamon Coffee-Bakery",
        area: "天河",
        district: "体育东路",
        address: "天河区体育东路48号（富丽花苑内）",
        lat: 23.132225,
        lng: 113.329021,
        tags: ["Dirty", "创意特调", "甜品面包"],
        priceRange: "¥20-45",
        rating: 4.5,
        recommendation: "前面包师打造的温暖社区店，招牌肉桂dirty与特色抹茶拿铁香气独特。",
        highlights: ["肉桂dirty", "抹茶拿铁", "每日现烤面包"],
        hours: "周一至周五 08:00-19:00；周六周日 10:00-19:00",
        metro: "近体育西路站",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2024-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "ssaw-coffee",
        name: "SSAW·四序咖啡",
        area: "荔湾",
        district: "永庆坊",
        address: "荔湾区恩宁路多宝南横9号",
        featured: true,
        lat: 23.116018,
        lng: 113.235817,
        tags: ["创意特调"],
        priceRange: "¥38-78",
        rating: 4.6,
        recommendation: "旧西关大屋改造，以四季为灵感的静谧庭院，特调与手冲茶极具东方韵味。",
        highlights: ["青山在特调", "手冲茶", "Combo"],
        hours: "周一至周日 10:00-20:30",
        metro: "黄沙站 B 出口步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2021-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "cafe-modori",
        name: "Cafe Modori 围巾咖啡屋",
        area: "越秀",
        district: "农讲所",
        address: "越秀区金鱼塘44号",
        lat: 23.124488,
        lng: 113.27225,
        tags: ["精品手冲", "自烘焙"],
        priceRange: "¥28-78",
        rating: 4.5,
        recommendation: "主理人希望“围巾”能像它给人的感觉一样，themselves是经验丰富的咖啡师和烘培师，会将比赛级的专业理念融入日常出品中",
        highlights: ["Combo", "手冲咖啡", "创意特调"],
        hours: "周一、周三至周日 10:00-19:00（周二店休）",
        metro: "农讲所站 D 口步行 470 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2023-06-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "kumquat-coffee",
        name: "金柑咖啡商店",
        area: "越秀",
        district: "农讲所",
        address: "越秀区文德路仁康里38号-2",
        lat: 23.12434,
        lng: 113.272811,
        tags: ["自烘焙", "精品手冲"],
        priceRange: "¥23-58",
        rating: 4.5,
        recommendation: "从永庆坊迁至农讲所的宝藏手冲店，歌单品味极佳，氛围像在大客厅里轻松交流，店里选豆多以外豆为主，像射手，sey，tant这些海外烘培商你都可以在这喝到",
        highlights: ["传统布丁", "手冲咖啡", "抹茶苹果汁", "海外咖啡豆"],
        hours: "周二至周日 11:00-18:00",
        metro: "农讲所站 D 口步行 470 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2023-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "flow-coffee",
        name: "FLOW 流点咖啡（东山口店）",
        area: "越秀",
        district: "东山口",
        address: "越秀区保安南街2-3号",
        lat: 23.120288,
        lng: 113.300227,
        tags: ["Combo", "创意特调"],
        priceRange: "¥28-45",
        rating: 4.5,
        recommendation: "滨江老店升级，蓝色飞鸟logo、清凉泳池风，夏季特调与奶油卷是绝配。",
        highlights: ["氮气Combo", "墨西哥树莓特调", "猫店长阿花", "奶油卷"],
        hours: "周一至周日 10:00-19:00",
        metro: "东山口站步行约 15 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2024-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "deeper-coffee",
        name: "deeper² Coffee",
        area: "越秀",
        district: "西门口",
        address: "越秀区福泉街18号105铺",
        featured: true,
        lat: 23.126911,
        lng: 113.259633,
        tags: ["创意特调", "意式单品（SOE）", "精品手冲"],
        priceRange: "¥38-78",
        rating: 4.6,
        recommendation: "上海OPS前咖啡师主理，自家烘焙的精品巧克力与热带风格特调不容错过。",
        highlights: ["一豆三喝", "精品手冲", "创意咖啡"],
        hours: "周一至周日 10:00-19:00",
        metro: "公园前站 L2 出口步行 500 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2023-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "round-to-coffee",
        name: "Round to Coffee",
        area: "越秀",
        district: "农讲所",
        address: "越秀区长塘街83号111铺",
        lat: 23.124865,
        lng: 113.272754,
        tags: ["Combo", "创意特调"],
        priceRange: "¥30-78",
        rating: 4.5,
        recommendation: "The Path Cafe前咖啡师打造，绿色原木风空间，创意特调与手工面包超治愈。",
        highlights: ["小白兔/小黑兔特调", "肉桂拿铁", "一豆三喝"],
        hours: "周一至周日 10:00-19:00",
        metro: "农讲所站 A 口步行 420 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2024-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "dang-coffee",
        name: "dang³ 凳仔咖啡",
        area: "天河",
        district: "六运小区",
        address: "天河区六运七街19号105",
        featured: true,
        lat: 23.130878,
        lng: 113.331699,
        tags: ["Combo", "意式单品（SOE）"],
        priceRange: "¥23-48",
        rating: 4.7,
        recommendation: "前JPG咖啡师团队作品，港式省凳元素反差拉满，特调gulu gulu极具创意。",
        highlights: ["Combo", "gulu gulu特调", "yellow drupe"],
        hours: "周一至周日 10:00-18:30",
        metro: "石牌桥站步行 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2024-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "jinli-erwei",
        name: "尽力而为咖啡",
        area: "海珠",
        district: "琶洲",
        address: "海珠区石基路610号/609号（近黄埔古港）",
        featured: true,
        lat: 23.087909,
        lng: 113.388334,
        tags: ["浅烘培", "精品手冲"],
        priceRange: "¥37-58",
        rating: 4.8,
        recommendation: "2023世界咖啡烘焙大赛中国冠军宋春丹主理，世界级手冲天堂。",
        highlights: ["kenya手冲咖啡", "巴拿马手冲咖啡"],
        hours: "周三店休；周一、二、四、五 10:00-19:00",
        metro: "近万胜围站",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: true },
        createdAt: "2023-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "renren-coffee",
        name: "忍忍咖啡",
        area: "越秀",
        district: "惠吉西",
        address: "越秀区惠吉西路23号102",
        lat: 23.126348,
        lng: 113.259228,
        tags: ["Dirty", "创意特调"],
        priceRange: "¥38-58",
        rating: 4.5,
        recommendation: "自带庭院的老城区咖啡馆，日系美学与静谧空间，是i人治愈地。",
        highlights: ["琥珀黄油脏Dirty", "手冲", "禁止蕉绿脏Dirty"],
        hours: "周一至周日 10:00-20:00",
        metro: "西门口站 B 口步行 420 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2021-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "lot3-coffee",
        name: "Lot#3",
        area: "海珠",
        district: "沙园",
        address: "海珠区沙渡路1号136",
        lat: 23.082474,
        lng: 113.254417,
        tags: ["自烘焙", "超萃咖啡", "精品手冲", "创意特调"],
        priceRange: "¥35-58",
        rating: 4.5,
        recommendation: "工业仓库改造，超萃咖啡是招牌，结合了日晒与水洗瑰夏的浓缩基底风味极佳。",
        highlights: ["超萃咖啡", "斑斓椰香拿铁", "自烘焙豆"],
        hours: "周一至周日 11:00-18:30",
        metro: "沙园站",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2025-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "rose-cafe",
        name: "玫瑰咖啡 ROSECAFE",
        area: "越秀",
        district: "中山六路",
        address: "越秀区中山六路惠和坊9号",
        lat: 23.124928,
        lng: 113.259124,
        tags: ["自烘焙", "精品手冲"],
        priceRange: "¥35-60",
        rating: 4.5,
        recommendation: "广州精品咖啡“鼻祖”，二十多年老字号，自家烘焙豆种类超百种，每杯咖啡都有独特“身份证”,为数不多有出品也门咖啡的门店",
        highlights: ["超百种自烘豆", "精品手冲", "咖啡豆", "咖啡器具研发"],
        hours: "周二至周日 12:00-20:30",
        metro: "西门口站 B 口步行 290 米",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: false, dessert: false, parking: false },
        createdAt: "2025-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "cobble-stone",
        name: "Cobble Stone Coffee 鹅卵石咖啡",
        area: "天河",
        district: "体育东路",
        address: "天河区体育东路72号1层",
        featured: true,
        lat: 23.118774,
        lng: 113.288948,
        tags: ["精品手冲", "创意特调", "Combo"],
        priceRange: "¥36-50",
        rating: 4.7,
        recommendation: "藏在街角的温暖社区店，门前弧形玻璃非常出片，手写菜单很有质感，combo性价比高。",
        highlights: ["美式复古风", "一豆三喝Combo", "精品手冲", "极浅烘"],
        hours: "周一至周日 10:30-20:30",
        metro: "石牌桥站 A 口步行 500 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2025-01-01",
        updatedAt: "2025-12-01",        photos: [],
    },
    {
        id: "wupai-signless",
        name: "无牌咖啡 SignlessCAFE",
        area: "越秀",
        district: "公园前",
        address: "越秀区起义路南朝新街5号一楼",
        featured: true,
        lat: 23.124429,
        lng: 113.263733,
        tags: ["自烘焙", "创意特调", "精品手冲"],
        priceRange: "¥20-45",
        rating: 4.7,
        recommendation: "藏在老城区巷子深处，门面无招牌正如其名，自烘豆品种丰富，手冲20元起性价比极高，由世界烘焙赛中国总决赛亚军冯璐主理。",
        highlights: ["Dirty", "乔治的臭脸特调", "手冲咖啡", "罐头蛋糕"],
        hours: "周一至周日 11:00-23:00（周二公休）",
        metro: "公园前站 J 口步行约 5 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "the-dose",
        name: "The Dose 豆事咖啡",
        area: "越秀",
        district: "北京路",
        address: "越秀区北京南路东横街1号",
        featured: false,
        closed: true,
        lat: 23.120267,
        lng: 113.271663,
        tags: ["精品手冲", "自烘焙"],
        priceRange: "¥28-58",
        rating: 4.7,
        recommendation: "北京路商圈藏在社区里的温柔小店，红砖外墙配大榕树户外座，咖啡师会耐心介绍每款豆子风味，香草云拿铁被誉为香草雪糕般浓郁顺滑。",
        highlights: ["香草云拿铁", "冰滴黑咖", "Combo", "Tasting Trio"],
        hours: "周一至周五 09:30-18:30；周六至周日 10:30-18:30",
        metro: "北京路站 B 口步行约 220 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "the-common-cup",
        name: "The Common Cup",
        area: "越秀",
        district: "西门口",
        address: "越秀区中山六路惠吉西二坊十一号一楼",
        featured: false,
        closed: true,
        lat: 23.126111,
        lng: 113.258855,
        tags: ["精品手冲", "自烘焙"],
        priceRange: "¥30-50",
        rating: 4.8,
        recommendation: "大隐于市的日系咖啡馆，藏身惠吉西居民巷内，低调无招牌，以精品手冲和自烘焙为主打，安静舒适适合独处。",
        highlights: ["单品手冲"],
        hours: "周一至周日 10:00-18:00",
        metro: "西门口站步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "jiezi-coffee",
        name: "芥子精品咖啡",
        area: "天河",
        district: "华康路",
        address: "天河区华康路（预约制，具体地址通过小程序获取）",
        featured: false,
        lat: 23.141958,
        lng: 113.330219,
        tags: ["精品手冲", "自烘焙"],
        priceRange: "¥88-228",
        rating: 4.7,
        recommendation: "『生如芥子，心藏须弥』日式板前预约制咖啡体验，广州少有的精品咖啡殿堂，提供顶级瑰夏等精品豆手冲与虹吸壶咖啡，需通过小程序预约。",
        highlights: ["板前手冲体验", "虹吸壶咖啡", "顶级瑰夏"],
        hours: "预约制，需通过小程序预订",
        metro: "体育中心站/石牌桥站",
        features: { wifi: true, powerOutlets: false, petFriendly: false, outdoor: false, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "sweetness-coffee",
        name: "Sweetness Coffee",
        area: "越秀",
        district: "东山口",
        address: "越秀区东华东路512号",
        featured: false,
        lat: 23.124487,
        lng: 113.290559,
        tags: ["精品手冲", "Dirty"],
        priceRange: "¥26-38",
        rating: 4.6,
        recommendation: "夫妻档经营的精品咖啡小店，搬了几次品质始终在线，以高性价比和稳定出品著称，Dirty和薛定谔系列特调是招牌。",
        highlights: ["Dirty", "茉莉雪梨拿铁", "薛定谔系列特调", "手冲单品咖啡"],
        hours: "周一至周日 10:00-18:00",
        metro: "东山口站步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "guanlin-qualia",
        name: "观粼 Qualia Cafe",
        area: "越秀",
        district: "海珠广场",
        address: "越秀区起义路维新横5号首层",
        featured: false,
        lat: 23.116467,
        lng: 113.265161,
        tags: ["甜品面包", "创意特调"],
        priceRange: "¥30-58",
        rating: 4.4,
        recommendation: "与美山婚礼公园同属一个主理人，主打精致法式甜品与精品咖啡，柚子抹茶聖多諾黑是招牌必点，阁楼空间温馨有格调。",
        highlights: ["柚子抹茶聖多諾黑", "罗勒柠檬挞", "半熟焙茶巴斯克", "日本焙茶拿铁"],
        hours: "周一至周日 11:00-21:00",
        metro: "海珠广场站 E 口步行约 5 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "silly-dog-coffee",
        name: "Silly Dog Coffee",
        area: "越秀",
        district: "农讲所",
        address: "越秀区中山四路大塘街24号101铺",
        featured: false,
        lat: 23.107975,
        lng: 113.285925,
        tags: ["精品手冲", "Dirty"],
        priceRange: "¥20-40",
        rating: 4.5,
        recommendation: "日式侘寂风宠物主题咖啡店，以狗狗为主题的温馨空间，开心果Dirty是招牌，复古氛围感满满。",
        highlights: ["开心果Dirty", "手冲咖啡"],
        hours: "周一至周日 11:00-19:00",
        metro: "农讲所站 A 口步行约 450 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "yuqiu-withchill",
        name: "屿秋 Withchill",
        area: "越秀",
        district: "中华广场",
        address: "越秀区中山三路北横街33号108房",
        featured: false,
        lat: 23.128076,
        lng: 113.279313,
        tags: ["创意特调"],
        priceRange: "¥28-45",
        rating: 4.5,
        recommendation: "充满秋意的社区咖啡店，位于东濠涌旁居民区，安静惬意，创意特调很值得一试。",
        highlights: ["创意特调"],
        hours: "周一至周日 11:00-20:00",
        metro: "烈士陵园站步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "c-stands-for",
        name: "C stands for",
        area: "越秀",
        district: "东华西路",
        address: "越秀区东华西路182号群星大厦首层",
        featured: true,
        lat: 23.128779,
        lng: 113.328601,
        tags: ["精品手冲", "自烘焙"],
        priceRange: "¥35-60",
        rating: 4.6,
        recommendation: "来自香港的主理人Steven打造，一张5.8米原木吧台拉近咖啡师与客人距离，搜罗世界各地烘焙商精品豆，是咖啡爱好者必去的宝藏店。",
        highlights: ["单品手冲"],
        hours: "周一至周日 10:00-18:00（周二公休）",
        metro: "烈士陵园站 A 口步行约 780 米",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: false, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "encore-anke",
        name: "Encore 谙客咖啡",
        area: "海珠",
        district: "江南西",
        address: "海珠区江南东路33号天汇大厦楼下商铺103号",
        featured: false,
        lat: 23.107361,
        lng: 113.26555,
        tags: ["精品手冲", "意式单品（SOE）"],
        priceRange: "¥25-45",
        rating: 4.4,
        recommendation: "江南西的精品咖啡馆，提供手冲与意式咖啡，出品平衡稳定。",
        highlights: ["手冲咖啡", "意式咖啡"],
        hours: "周一至周日 10:00-19:00",
        metro: "江南西站步行约 8 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "dirty-paws",
        name: "Dirty Paws 脏爪子咖啡",
        area: "海珠",
        district: "赤岗",
        address: "赤岗二街12号101",
        featured: false,
        lat: 23.0904,
        lng: 113.3287,
        tags: ["精品手冲", "超萃咖啡", "浅烘培"],
        priceRange: "¥20-40",
        rating: 4.5,
        recommendation: "附近街坊都很喜欢来的咖啡店，主打超萃咖啡和精品手冲",
        highlights: ["超萃咖啡，精品手冲"],
        hours: "周二至周五 09：00-17：00；周六周日 10：00-17：30",
        metro: "赤岗站步行约20分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "dream-high",
        name: "梦想舍 Dream High",
        area: "海珠",
        district: "滨江",
        address: "海珠区草芳围滨江婚育文化园46号",
        featured: false,
        lat: 23.111218,
        lng: 113.273905,
        tags: ["自烘焙", "精品手冲"],
        priceRange: "¥28-68",
        rating: 4.6,
        recommendation: "广州十年老牌自家烘焙精品咖啡馆，独栋老洋房带庭院天台，店主木子是广州咖啡圈知名烘焙师，豆子曾获WBC冠军肯定。",
        highlights: ["花木兰Dirty", "手冲咖啡", "法式苹果派", "桂花美式"],
        hours: "周一至周日 11:00-20:00",
        metro: "海珠广场站/市二宫站",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "xu-sidetrack",
        name: "墟 Sidetrack Cafe",
        area: "越秀",
        district: "北京路",
        address: "越秀区东横街18号101",
        featured: false,
        lat: 23.11999,
        lng: 113.271149,
        tags: ["创意特调"],
        priceRange: "¥35-55",
        rating: 4.5,
        recommendation: "藏身居民楼的中式庭院风复古咖啡店，以港乐主题和创意特调出名，店内还有黄色老式钢琴等打卡角落。",
        highlights: ["神爱世人特调咖啡", "半生瓜特调咖啡"],
        hours: "周一至周日 10:30-19:00",
        metro: "北京路站步行约 5 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "liangzhazha",
        name: "梁渣渣咖啡店",
        area: "越秀",
        district: "东山口",
        address: "越秀区东华东路554号",
        featured: false,
        lat: 23.120968,
        lng: 113.291097,
        tags: ["精品手冲"],
        priceRange: "¥20-34",
        rating: 4.5,
        recommendation: "东山口撸猫圣地+精品咖啡店，店内约有5只猫咪（多为加菲猫），咖啡品质不错，竹炭抹茶蛋糕卷是招牌甜品。",
        highlights: ["Combo", "海盐巧克力蛋糕卷", "竹炭抹茶蛋糕卷"],
        hours: "周一至周日 11:00-22:00",
        metro: "东山口站步行约 8 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: false, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "bean-plus",
        name: "豆荚咖啡 Bean+Coffee",
        area: "越秀",
        district: "西门口",
        address: "越秀区中山六路惠吉西36号",
        featured: false,
        lat: 23.126529,
        lng: 113.259514,
        tags: ["自烘焙", "精品手冲"],
        priceRange: "¥23-38",
        rating: 4.7,
        recommendation: "惠吉西社区咖啡店，所有咖啡豆在店内现场烘焙保证新鲜，店内银渐层猫咪「喝喝」性格温顺可撸，阿芙佳朵是招牌。",
        highlights: ["阿芙佳朵", "手冲咖啡"],
        hours: "周一至周日 10:00-19:00",
        metro: "西门口站 B 口步行约 460 米",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "bulldong-coffee",
        name: "Bulldong 布豆咖啡",
        area: "越秀",
        district: "纪念堂",
        address: "越秀区百灵路兴隆西三巷1-103",
        featured: false,
        lat: 23.131463,
        lng: 113.259496,
        tags: ["Combo", "精品手冲"],
        priceRange: "¥30-42",
        rating: 4.5,
        recommendation: "从佛山搬到广州的精品咖啡，以咖啡Combo（一豆两饮/一豆三饮）为主打，性价比高，纸杯Logo设计灵感源自世界名画。",
        highlights: ["桃乐茜Combo", "西达摩Combo", "一豆多饮"],
        hours: "周一至周日 10:00-19:00",
        metro: "纪念堂站步行约 10 分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: true, dessert: false, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "cupee",
        name: "Cupee",
        area: "增城",
        district: "荔城",
        address: "增城区荔城街荔乡路5号",
        featured: false,
        lat: 23.291261,
        lng: 113.825567,
        tags: ["精品手冲", "甜品面包"],
        priceRange: "¥20-40",
        rating: 4.5,
        recommendation: "增城宝藏社区咖啡店，暗黑风装修，甜品选择多，藏匿在城市的角落，每一口咖啡都是老板对豆子的理解。",
        highlights: ["手冲咖啡", "肉桂生姜Dirty"],
        hours: "周一至周日 13:00-18:30, 20:00-00:00",
        metro: "增城广场站打车约10分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "sheung-cafe",
        name: "Sheung Cafe",
        area: "增城",
        district: "荔城",
        address: "增城区荔城街道侨中路西巷31号一层",
        featured: false,
        lat: 23.2826,
        lng: 113.823724,
        tags: ["精品手冲", "甜品面包"],
        priceRange: "¥28-41",
        rating: 4.5,
        recommendation: "增城日系原木风温馨小店，环境治愈适合安静叹啡，焦糖杏仁戚风蛋糕好评度高。",
        highlights: ["培茶拿铁", "焦糖杏仁戚风蛋糕", "抹茶拿铁"],
        hours: "工作日 09:30-18:00（周二公休）；周末 13:00-19:00",
        metro: "增城广场站打车约10分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "iffy-coffee",
        name: "Iffy",
        area: "增城",
        district: "荔城",
        address: "荔城街洋角街41-25号",
        featured: false,
        lat: 23.2810,
        lng: 113.8221,
        tags: ["精品手冲"],
        priceRange: "¥25-45",
        rating: 4.5,
        recommendation: "主打手冲的咖啡店，，有很多在线的咖啡豆选怎，复古红色调风格，隐秘在城市中的极致阳光小店，相邻小河",
        highlights: ["精品手冲", "黄花特调咖啡"],
        hours: "10:00-18:00 店休看老板心情",
        metro: "增城广场打车10分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: true, outdoor: true, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    },
    {
        id: "jingtong-coffee",
        name: "景桐咖啡",
        area: "增城",
        district: "荔城",
        address: "荔城街金竹一路106号",
        featured: false,
        lat: 23.2879,
        lng: 113.8092,
        tags: ["精品手冲", "创意特调"],
        priceRange: "¥25-45",
        rating: 4.6,
        recommendation: "一家日式原木风的咖啡店，店内很安静，像误入小京都，主打特调",
        highlights: ["morning特调咖啡", "afternoon特调咖啡", "evening特调咖啡", "mellow rain特调咖啡", "influence特调咖啡"],
        hours: "10：00-19:00 店休看老板心情",
        metro: "增城广场打车10分钟",
        features: { wifi: true, powerOutlets: true, petFriendly: false, outdoor: false, dessert: true, parking: false },
        createdAt: "2026-06-13",
        updatedAt: "2026-06-13",        photos: [],
    }
];

// 区域定义
const AREAS = [
    { name: "天河", description: "CBD核心区，精品咖啡密度最高" },
    { name: "越秀", description: "老城区新活力，独立咖啡纷纷扎堆" },
    { name: "海珠", description: "文艺气息浓厚，隐藏宝藏多" },
    { name: "荔湾", description: "西关风情与咖啡的碰撞" },
    { name: "白云", description: "新兴咖啡势力" },
    { name: "番禺", description: "大学城周边年轻氛围" },
    { name: "黄埔", description: "科学城与老黄埔的咖啡新势力" },
    { name: "南沙", description: "自贸区里的咖啡新天地" },
    { name: "花都", description: "北站新城的咖啡探索" },
    { name: "增城", description: "荔城与新塘的咖啡萌芽" },
    { name: "从化", description: "温泉小镇的悠闲咖啡时光" },
];

// 标签分类 — 仅保留咖啡风格
const TAG_CATEGORIES = [
    {
        name: "咖啡风格",
        tags: ["精品手冲", "意式单品（SOE）", "自烘焙", "创意特调", "浅烘培", "Combo", "Dirty", "超萃咖啡", "甜品面包"]
    },
];

// 卡片背景色（给没有图片的店铺用）
const CARD_COLORS = [
    "linear-gradient(135deg, #E8E0D4 0%, #C4B9A8 100%)",
    "linear-gradient(135deg, #E8EFF6 0%, #A8C4D8 100%)",
    "linear-gradient(135deg, #E8EDE3 0%, #B8C8A8 100%)",
    "linear-gradient(135deg, #F5EDD8 0%, #D4C4A0 100%)",
    "linear-gradient(135deg, #F8E8E2 0%, #D8B8A8 100%)",
    "linear-gradient(135deg, #EDE8F0 0%, #C4B8D0 100%)",
    "linear-gradient(135deg, #F0EDE8 0%, #D0C8B8 100%)",
    "linear-gradient(135deg, #E5EBE8 0%, #B8CCC0 100%)",
];
